FROM mcr.microsoft.com/dotnet/aspnet:8.0 as base

EXPOSE 80
ENV ASPNETCORE_URLS=http://+:5000
ENV ASPNETCORE_ENVIRONMENT=Development

WORKDIR /app
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["CarsApi/CarsApi.csproj","CarsApi/"]
RUN dotnet restore "CarsApi/CarsApi.csproj"

COPY . . 
FROM build as publish
RUN dotnet publish "CarsApi/CarsApi.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base as final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CarsApi.dll"]